targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/integrations/*.dart
      json_serializable:
        generate_for:
          - lib/integrations/*.dart
      retrofit_generator:
        generate_for:
          - lib/integrations/*.dart
