# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true

coverage:
  status:
    # Project coverage: overall repository coverage
    project:
      default:
        target: 99%       # Minimum baseline threshold
        threshold: 1%     # Allow 1% drop (common in small packages)

    # Patch coverage: coverage of new/changed lines only
    patch:
      default:
        target: 99%       # New code should be well-tested

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true   # Only comment when coverage changes
